version: '3.8'
services:
  app:
    build:
      context: ./
    volumes:
      - .:/src
    env_file:
      - .env.local
    command: npm run dev:server
    environment:
      NODE_ENV: development
    ports:
      - 8000:8000
